"""empty message

Revision ID: 04062987acde
Revises: 67f495684084
Create Date: 2019-01-20 16:50:47.543900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04062987acde'
down_revision = '67f495684084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
