"""empty message

Revision ID: 85a6c5346197
Revises: 04062987acde
Create Date: 2019-01-23 13:55:17.922299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85a6c5346197'
down_revision = '04062987acde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('defualt', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_defualt'), 'roles', ['defualt'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_defualt'), table_name='roles')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'defualt')
    # ### end Alembic commands ###
