"""empty message

Revision ID: a82a7c080b9c
Revises: 4444004e4702
Create Date: 2019-01-27 17:40:07.882058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a82a7c080b9c'
down_revision = '4444004e4702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    op.drop_column('posts', 'html_body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('html_body', sa.TEXT(), nullable=True))
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
